services:
  main-service:
    build: 
      context: ..
      args:
        SERVICE_NAME: openmemory
      dockerfile: docker/Dockerfile
    ports:
      - "${PORT:-8000}:8000"
    environment:
      # Override or set other environment variables in .env
      - ENVIRONMENT=${ENVIRONMENT:-local}
      - PORT=${PORT:-8000}
      - BIND_PUBLIC_HOST=${BIND_PUBLIC_HOST:-True}
      - DISABLE_HEALTH_CHECK_ACCESS_LOGS=${DISABLE_HEALTH_CHECK_ACCESS_LOGS:-False}
      - DD_TRACE_ENABLED=${DD_TRACE_ENABLED:-False}
      - DD_ENV=local
      - DD_VERSION=0.0.0
    env_file:
      - ../.env
    volumes:
      - ${HOME}/.aws:/srv/openmemory/.aws:ro
    # secrets:
    #   - EXAMPLE_SECRET
    healthcheck:
      test: curl -f http://localhost:${PORT:-8000}/health -A container-health-check
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - mcp_network
    stdin_open: true # docker run -i
    tty: true        # docker run -t

networks:
  mcp_network:
    driver: bridge

# secrets:
#   EXAMPLE_SECRET:
#     file: ../secrets/EXAMPLE_SECRET
